### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by futuresocks** [rdtclark/ccps#1]
Really impressed with this - great job!

At the moment, viewing the site on mobile can be tricky due to fitting the two containers side by side on the screen. Is it worth considering using React Router to split the Employers and Jobs out to different routes so that only one is viewable at a time? Or failing that, perhaps just using some CSS to change the layout of the containers on mobile so that they appear vertically one after the other?

**Comment by rdtclark** [comment]
Many thanks for the suggestions.

I think we will try both approaches and see what works best. 

Who doesn't love a a burger menu as well. @nmackenzie91

**Comment by nmackenzie91** [comment]
Thanks for the kind words and the suggestions! Sorry for the delay but I've now added a Router so that the Employers and Jobs are split as well as updating the CSS so that the Employers' page is displayed differently on mobile devices.
